Replace horizon calls with RPC
stellar/wallet-backend pull request #93
Opened 2024-12-19 10:42 UTC by aditya1702

### What

[TODO: Short statement about what is changing.]

### Why

[TODO: Why this change is being made. Include any context required to understand the why.]

### Known limitations

[TODO or N/A]

### Issue that this PR addresses

[TODO: Attach the link to the GitHub issue or task. Include the priority of the task here in addition to the link.]

### Checklist

#### PR Structure

- [ ] It is not possible to break this PR down into smaller PRs.
- [ ] This PR does not mix refactoring changes with feature changes.
- [ ] This PR's title starts with name of package that is most changed in the PR, or `all` if the changes are broad or impact many packages.

#### Thoroughness

- [ ] This PR adds tests for the new functionality or fixes.
- [ ] All updated queries have been tested (refer to [this](https://stackoverflow.com/a/29163465) check if the data set returned by the updated query is expected to be same as the original one).

#### Release

- [ ] This is not a breaking change.
- [ ] This is ready to be tested in development.
- [ ] The new functionality is gated with a feature flag if this is not ready for production.

2025-01-02 22:26 UTC, JakeUrban reviewed
This looks mostly good! Just a couple minor comments and one more meaningful question.

2025-01-02 22:26 UTC, JakeUrban commented on internal/services/channel_account_service.go
> +		txResult, err := s.RPCService.GetTransaction(payload.TransactionHash)
Is this approach used elsewhere in the codebase?

It seems odd to me that we are submitting a request to the TSS but getting the result from RPC. I would have figured that the TSS would provide a way to fetch transaction results, or even sent the result back to client who requested it be submitted.

Golang's channels seem like the right choice for something like this.

- client asks for a channel from the tss
- tss provides a golang channel
- client provides the transaction to the tss via the channel
- tss sends the transaction results back over the same channel

This would allow us to avoid polling RPC directly and instead just wait for a response on the channel provided to use from the TSS service.

2025-01-02 22:26 UTC, JakeUrban commented on internal/utils/utils.go
> +	copy(key[:], decoded)
Why are we copying `decoded` into `key`?

2025-01-03 16:47 UTC, aditya1702 commented on internal/services/account_sponsorship_service.go
> +	if err.Error() != accountNotFoundError {
Ah good catch. Yeah the idiomatic way is to use `errors.Is` instead. I used this way to make sure the code was working but did not realise the negatives of using it. Thanks for spotting

2025-01-03 18:02 UTC, aditya1702 commented on internal/utils/utils.go
> +	copy(key[:], decoded)
Because `decoded` is a byte array and `key` is a fixed size [32]byte array. In order to convert slice to fixed size, the recommended way would be to use `copy()`: https://stackoverflow.com/questions/30285680/how-to-convert-slice-to-fixed-size-array.

We can also use something like this - `key = *(*[32]byte)(decoded)` but `copy()` would be cleaner

2025-01-03 18:21 UTC, aditya1702 commented on internal/serve/serve.go
> +	httpClient := http.Client{Timeout: time.Duration(30 * time.Second)}
Hmm, this line was not added by me. I just rearranged the code lines in this diff. Maybe @gouthamp-stellar could answer this? From the code, it looks like we define a client for new services like the [rpcService](https://github.com/stellar/wallet-backend/blob/main/internal/serve/serve.go#L206) and [webHook channel](https://github.com/stellar/wallet-backend/blob/main/internal/serve/serve.go#L245)

2025-01-03 19:01 UTC, aditya1702 commented on internal/services/channel_account_service.go
> +		txResult, err := s.RPCService.GetTransaction(payload.TransactionHash)
@JakeUrban So this approach is actually what I started with and the design also makes sense. The TSS has been configured in a way where we provide a webhook URL to the router in the payload [here](https://github.com/stellar/wallet-backend/blob/main/internal/tss/types.go#L195). This fits into the design of TSS where clients would then listen to this webhook to get updates on the txns they have submitted . The solution would be to write a webhook handler and use a go channel to keep checking for the transaction status update on the URL. (correct me if I am wrong here @gouthamp-stellar )

In this case, however, the channel account txn is only submitted once during the initial starting of wallet-backend server. So implementing a new webhook handler and channels to just poll for this one txn seemed too much and I instead just used the `GetTransaction` to look for the txn.

But we can definitely discuss and change it accordingly

2025-01-03 19:10 UTC, aditya1702 commented on internal/services/rpc_service.go
> +func (r *rpcService) GetAccountLedgerSequence(address string) (int64, error) {
Because currently the only use case for getting an account is to get its latest sequence number. I decided to just add function for that and we can always change the definition in the future to return account object with the other details. What do you think?

2025-01-04 01:07 UTC, JakeUrban commented on internal/services/rpc_service.go
> +func (r *rpcService) GetAccountLedgerSequence(address string) (int64, error) {
Fine by me

2025-01-04 01:09 UTC, JakeUrban commented on internal/services/channel_account_service.go
> +		txResult, err := s.RPCService.GetTransaction(payload.TransactionHash)
Maybe we should just submit to RPC rather than use half of the TSS solution (submission but not results)

2025-01-06 16:13 UTC, aditya1702 commented on internal/services/channel_account_service.go
> +		txResult, err := s.RPCService.GetTransaction(payload.TransactionHash)
@JakeUrban That is not as straightforward as it sounds because in that case, we have to handle all the retries and resubmissions based on the status that RPC sends. The TSS does this automatically through its channels implementation. That is why using TSS for submission is the cleaner approach here.

@gouthamp-stellar do you have any thoughts on this issue?

2025-01-06 17:10 UTC, aditya1702 commented on internal/entities/rpc.go
> +	DataXDR            string `json:"xdr,omitempty"`
Yes that is true but this is defined directly in the RPC codebase [here](https://github.com/stellar/stellar-rpc/blob/main/cmd/stellar-rpc/internal/methods/get_ledger_entries.go#L27) so I kept it as is

2025-01-06 21:35 UTC, gouthamp-stellar commented on internal/services/rpc_service.go
> +
nit: I do like the idea of this function, but I wonder if it should also be in utils.go, because I feel like it is essentially just parsing an rpc response

2025-01-06 22:46 UTC, gouthamp-stellar commented on internal/services/channel_account_service.go
> +		txResult, err := s.RPCService.GetTransaction(payload.TransactionHash)
I think we should either use TSS or RPC for this, and not both. 

If we went the TSS route, instead of polling RPC's GetTransaction, we could poll the tss/transactions/{transactionhash} endpoint till we get a 'SUCCESS' response. The tss/transactions/{transactionhash} endpoint looks up the transaction in the tss transactions table, which is updated by TSS/the ingestor. Or you could repeatedly poll the tss transactions table yourself 

If we go with using RPC directly, we may be able to get away with something simple here like using rpc_service.go's SendTransaction and call GetTransaction in a loop. Basically, instead of submitting the transaction to the router like you currently are, submit it to RPC directly

I think the RPC approach is cleaner. I get that it's possible that we'll have cases where we'll have to retry and resubmit, but it's just a single transaction that we send upon startup. I think using TSS, which is really meant for high volume transaction submission, is a little overkill

2025-01-07 04:06 UTC, gouthamp-stellar commented
One thing to note here is that if we are using RPC, we need to be sure that it is ready (ie gethealth returns a positive result), which can take upto a few minutes if I'm not mistaken. So you may not be able to create all those channel accounts as soon as wallet backend starts up - you'd have to wait till RPC is ready to create those channel accounts right?

2025-01-07 16:09 UTC, gouthamp-stellar requested changes
take a look at my comments

2025-01-08 21:11 UTC, gouthamp-stellar commented on internal/services/channel_account_service.go
> +	err := waitForRPCServiceHealth(ctx, s.RPCService)
will this wait indefinitely till RPC is healthy? If so, is it possible that it will wait for a long time since RPC can take a while to get healthy?

2025-01-08 21:16 UTC, gouthamp-stellar commented on internal/services/channel_account_service.go
> +func (s *channelAccountService) getTransactionStatus(_ context.Context, hash string) error {
maybe this should be named something like ensureTransactionSuccess, since it doesn't actually get a transaction's status but rather repeatedly pings RPC's GetTransaction till it returns a success. Wdty?

2025-01-08 22:09 UTC, aditya1702 commented on internal/services/channel_account_service.go
> +func (s *channelAccountService) getTransactionStatus(_ context.Context, hash string) error {
Hmm, yeah thats a good suggestion.

2025-01-08 22:13 UTC, aditya1702 commented on internal/services/channel_account_service.go
> +	err := waitForRPCServiceHealth(ctx, s.RPCService)
@gouthamp-stellar It would wait till the ctx is cancelled [here](https://github.com/stellar/wallet-backend/pull/93/files#diff-ee84d6b11d3ccdf80838be43c58eedc317f6c196f2ce5ebd627e06ec42c00a97R157). However, I am realising now that `ctx` is a `context.Background()` which does not have a default timeout. So we will have to add our own timeout here to make sure it exits

2025-01-08 22:47 UTC, JakeUrban commented on internal/services/channel_account_service.go
> +	err := waitForRPCServiceHealth(ctx, s.RPCService)
To clarify, if we reach the timeout, we would exit the process and log some error about the RPC being unavailable?

2025-01-08 22:48 UTC, JakeUrban commented on internal/services/channel_account_service.go
> +	err := waitForRPCServiceHealth(ctx, s.RPCService)
Nvm, the code speaks for itself

2025-01-08 22:48 UTC, JakeUrban approved these changes

2025-01-08 23:08 UTC, gouthamp-stellar commented on internal/services/channel_account_service.go
> +	err := waitForRPCServiceHealth(ctx, s.RPCService)
If rpc does not get healthy within these 5 minutes, then it seems like the channel accounts won't get created, right? If that's the case, it may be worth it to have ensureChannelAccounts (https://github.com/stellar/wallet-backend/blob/main/internal/serve/serve.go#L302) be called on a ticker or something, throughout the lifespan of the wallet backend. Unless we can be sure that RPC will get healthy within the 5 minutes.

2025-01-10 05:30 UTC, gouthamp-stellar approved these changes

2025-01-10 16:10 UTC, merged